name: Deploy DocFX to GitHub Pages

on:
  push:
    branches:
      - feature/api-reference
  release: 
    types:
      - released

concurrency: 
  group: pages
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}
    permissions:
      pages: write
      contents: write
      id-token: write # Required for GitHub Pages deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Or the .NET version required by DocFX

      - name: Install DocFX
        run: dotnet tool install --global docfx

      - name: Build DocFX Documentation
        run: docfx docfx.json
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: 'api-reference/_site'
      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v4
          
        
#      - name: Deploy to GitHub Pages
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: api-reference/_site # Path to your DocFX output folder
#          #force_orphan: true # Recommended for clean deployments